export const defaultData =[
    {
        "denNgayTheBhyt": "2022-11-02",
        "tienNbTuTra": 28001920,
        "k": [
            {
                "tienNguonKhac": 0,
                "tienBhThanhToan": 36765,
                "tongTien": 38700,
                "tienNbTuTra": 0,
                "tenKhoaChiDinh": "Khoa Khám Bệnh",
                "tienNb": 1935,
                "tongTienBh": 38700,
                "n": [
                    {
                        "tienNguonKhac": 0,
                        "tienBhThanhToan": 36765,
                        "tongTien": 38700,
                        "tienNbTuTra": 0,
                        "ktc": [
                            {
                                "tienNguonKhac": 0,
                                "s": [
                                    {
                                        "tienNguonKhac": 0,
                                        "dv": [
                                            {
                                                "id": 353272,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Ngoại trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": null,
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "02.1896iu",
                                                "tenDichVu": "Khám Nội",
                                                "dichVuId": 3124,
                                                "loaiDichVu": "Khám",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T10:57:14+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:57:52+07:00",
                                                "giaKhongBaoHiem": 450000,
                                                "giaBaoHiem": 38700,
                                                "giaPhuThu": 0,
                                                "tyLeBhTt": 100,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 0,
                                                "tienNbPhuThu": 0,
                                                "tienNbCungChiTra": 1935,
                                                "tienBhThanhToan": 36765,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 1935,
                                                "tongTien": 38700,
                                                "tienNb": 1935,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 118906,
                                                "chiDinhTuLoaiDichVu": "Tiếp đón",
                                                "khoaChiDinhId": 52,
                                                "tenKhoaChiDinh": "Khoa Khám Bệnh",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 109,
                                                "tenDonViTinh": "Lần",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 14,
                                                "nhomDichVuCap2Id": 107,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Khám bệnh",
                                                "tenNhomDichVuCap2": "Khám bệnh thường",
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": "Đã kết luận",
                                                "trangThaiXuatKho": null,
                                                "loaiNhapXuat": null,
                                                "sttBangKe": 1,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": 160,
                                                "maPhongThucHien": "P105.1",
                                                "tenPhongThucHien": "Phòng 105 - Bàn 1 (BS Hoàn)",
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": "Nhập viện",
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": null,
                                                "soPhieuId": null,
                                                "soKetNoi": null,
                                                "thanhToanSau": true,
                                                "kyThuatCao": false,
                                                "stent2": false,
                                                "thoiGianYLenh": null,
                                                "bacSiKhamId": 14,
                                                "tenBacSiKham": "Phạm Văn Minh",
                                                "noiTru": false,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 38700,
                                                "tongTienBh": 38700
                                            }
                                        ],
                                        "tienBhThanhToan": 36765,
                                        "tongTien": 38700,
                                        "tienNbTuTra": 0,
                                        "tienNb": 1935,
                                        "tongTienBh": 38700,
                                        "tienNbCungChiTra": 1935,
                                        "tienMienGiam": 0
                                    }
                                ],
                                "tienBhThanhToan": 36765,
                                "tongTien": 38700,
                                "tienNbTuTra": 0,
                                "tienNb": 1935,
                                "tongTienBh": 38700,
                                "tienNbCungChiTra": 1935,
                                "tienMienGiam": 0
                            }
                        ],
                        "tienNb": 1935,
                        "tongTienBh": 38700,
                        "tenNhomDichVuCap1": "1. Khám bệnh",
                        "tienNbCungChiTra": 1935,
                        "tienMienGiam": 0
                    }
                ],
                "tienNbCungChiTra": 1935,
                "tienMienGiam": 0
            },
            {
                "tienNguonKhac": 0,
                "tienBhThanhToan": 9501824,
                "tongTien": 20003840,
                "tienNbTuTra": 10001920,
                "tenKhoaChiDinh": "Khoa Phẫu Thuật Tim Mạch & Lồng Ngực Người Lớn",
                "tienNb": 10502016,
                "tongTienBh": 10003840,
                "n": [
                    {
                        "tienNguonKhac": 0,
                        "tienBhThanhToan": 9500000,
                        "tongTien": 20000000,
                        "tienNbTuTra": 10000000,
                        "ktc": [
                            {
                                "tienNguonKhac": 0,
                                "s": [
                                    {
                                        "tienNguonKhac": 0,
                                        "dv": [
                                            {
                                                "id": 353215,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Điều trị nội trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": [
                                                    11047
                                                ],
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "dvk002",
                                                "tenDichVu": "Phẫu thuật mổ nội soi hỗ trợ trong phẫu thuật tim hở",
                                                "dichVuId": 6876,
                                                "loaiDichVu": "Phẫu thuật - Thủ thuật",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T10:59:09+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:59:25+07:00",
                                                "giaKhongBaoHiem": 20000000,
                                                "giaBaoHiem": 10000000,
                                                "giaPhuThu": 10000000,
                                                "tyLeBhTt": 100,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 10000000,
                                                "tienNbPhuThu": 10000000,
                                                "tienNbCungChiTra": 500000,
                                                "tienBhThanhToan": 9500000,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 10500000,
                                                "tongTien": 20000000,
                                                "tienNb": 10500000,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 38902,
                                                "chiDinhTuLoaiDichVu": "Tờ điều trị",
                                                "khoaChiDinhId": 55,
                                                "tenKhoaChiDinh": "Khoa Phẫu Thuật Tim Mạch & Lồng Ngực Người Lớn",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 109,
                                                "tenDonViTinh": "Lần",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 23,
                                                "nhomDichVuCap2Id": 122,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Phẫu thuật",
                                                "tenNhomDichVuCap2": "Phẫu thuật",
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": "Đã tiếp nhận",
                                                "trangThaiXuatKho": null,
                                                "loaiNhapXuat": null,
                                                "sttBangKe": 6,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": 209,
                                                "maPhongThucHien": "1000010",
                                                "tenPhongThucHien": "Phòng gây mê hồi sức (Phòng TT)",
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": null,
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": 33453,
                                                "soPhieuId": 202356,
                                                "soKetNoi": null,
                                                "thanhToanSau": true,
                                                "kyThuatCao": false,
                                                "stent2": false,
                                                "thoiGianYLenh": "2022-10-31T10:58:49+07:00",
                                                "bacSiKhamId": null,
                                                "tenBacSiKham": null,
                                                "noiTru": true,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 20000000,
                                                "tongTienBh": 10000000
                                            }
                                        ],
                                        "tienBhThanhToan": 9500000,
                                        "tongTien": 20000000,
                                        "tienNbTuTra": 10000000,
                                        "tienNb": 10500000,
                                        "tongTienBh": 10000000,
                                        "tienNbCungChiTra": 500000,
                                        "tienMienGiam": 0
                                    }
                                ],
                                "tienBhThanhToan": 9500000,
                                "tongTien": 20000000,
                                "tienNbTuTra": 10000000,
                                "tienNb": 10500000,
                                "tongTienBh": 10000000,
                                "tienNbCungChiTra": 500000,
                                "tienMienGiam": 0
                            }
                        ],
                        "tienNb": 10500000,
                        "tongTienBh": 10000000,
                        "tenNhomDichVuCap1": "6. Phẫu thuật",
                        "tienNbCungChiTra": 500000,
                        "tienMienGiam": 0
                    },
                    {
                        "tienNguonKhac": 0,
                        "tienBhThanhToan": 1824,
                        "tongTien": 3840,
                        "tienNbTuTra": 1920,
                        "ktc": [
                            {
                                "tienNguonKhac": 0,
                                "s": [
                                    {
                                        "tienNguonKhac": 0,
                                        "dv": [
                                            {
                                                "id": 353218,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Điều trị nội trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": [
                                                    11047
                                                ],
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "ACTELSAR40",
                                                "tenDichVu": "Actelsar 40mg",
                                                "dichVuId": 5059,
                                                "loaiDichVu": "Thuốc",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T11:01:17+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:58:49+07:00",
                                                "giaKhongBaoHiem": 3840,
                                                "giaBaoHiem": 3840,
                                                "giaPhuThu": 0,
                                                "tyLeBhTt": 50,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 1920,
                                                "tienNbPhuThu": 0,
                                                "tienNbCungChiTra": 96,
                                                "tienBhThanhToan": 1824,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 2016,
                                                "tongTien": 3840,
                                                "tienNb": 2016,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 38902,
                                                "chiDinhTuLoaiDichVu": "Tờ điều trị",
                                                "khoaChiDinhId": 55,
                                                "tenKhoaChiDinh": "Khoa Phẫu Thuật Tim Mạch & Lồng Ngực Người Lớn",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 209,
                                                "tenDonViTinh": "Viên",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 21,
                                                "nhomDichVuCap2Id": null,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Thuốc, dịch truyền",
                                                "tenNhomDichVuCap2": null,
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": null,
                                                "trangThaiXuatKho": "Hoàn thành",
                                                "loaiNhapXuat": "NB tủ trực",
                                                "sttBangKe": 8,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": null,
                                                "maPhongThucHien": null,
                                                "tenPhongThucHien": null,
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": null,
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": 33453,
                                                "soPhieuId": null,
                                                "soKetNoi": null,
                                                "thanhToanSau": null,
                                                "kyThuatCao": false,
                                                "stent2": false,
                                                "thoiGianYLenh": "2022-10-31T10:58:49+07:00",
                                                "bacSiKhamId": null,
                                                "tenBacSiKham": null,
                                                "noiTru": true,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 3840,
                                                "tongTienBh": 3840
                                            }
                                        ],
                                        "tienBhThanhToan": 1824,
                                        "tongTien": 3840,
                                        "tienNbTuTra": 1920,
                                        "tienNb": 2016,
                                        "tongTienBh": 3840,
                                        "tienNbCungChiTra": 96,
                                        "tienMienGiam": 0
                                    }
                                ],
                                "tienBhThanhToan": 1824,
                                "tongTien": 3840,
                                "tienNbTuTra": 1920,
                                "tienNb": 2016,
                                "tongTienBh": 3840,
                                "tienNbCungChiTra": 96,
                                "tienMienGiam": 0
                            }
                        ],
                        "tienNb": 2016,
                        "tongTienBh": 3840,
                        "tenNhomDichVuCap1": "8. Thuốc, dịch truyền",
                        "tienNbCungChiTra": 96,
                        "tienMienGiam": 0
                    }
                ],
                "tienNbCungChiTra": 500096,
                "tienMienGiam": 0
            },
            {
                "tienNguonKhac": 0,
                "tienBhThanhToan": 71250000,
                "tongTien": 93000000,
                "tienNbTuTra": 18000000,
                "tenKhoaChiDinh": "Khoa Gây Mê Hồi Sức",
                "tienNb": 21750000,
                "tongTienBh": 93000000,
                "n": [
                    {
                        "tienNguonKhac": 0,
                        "tienBhThanhToan": 71250000,
                        "tongTien": 93000000,
                        "tienNbTuTra": 18000000,
                        "ktc": [
                            {
                                "tienNguonKhac": 0,
                                "tenPtTt": "Phẫu thuật mổ nội soi hỗ trợ trong phẫu thuật tim hở",
                                "tenGoiVatTuKtc": "10.1. Gói vật tư y tế 1",
                                "s": [
                                    {
                                        "tienNguonKhac": 0,
                                        "dv": [
                                            {
                                                "id": 353216,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Điều trị nội trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": null,
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "vtktc3",
                                                "tenDichVu": "Vật tư ktc 2",
                                                "dichVuId": 19002,
                                                "loaiDichVu": "Vật tư",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T11:00:24+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:59:25+07:00",
                                                "giaKhongBaoHiem": 3060000,
                                                "giaBaoHiem": 3000000,
                                                "giaPhuThu": 0,
                                                "tyLeBhTt": 100,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 0,
                                                "tienNbPhuThu": 0,
                                                "tienNbCungChiTra": 150000,
                                                "tienBhThanhToan": 2850000,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 150000,
                                                "tongTien": 3000000,
                                                "tienNb": 150000,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 353215,
                                                "chiDinhTuLoaiDichVu": "Phẫu thuật - Thủ thuật",
                                                "khoaChiDinhId": 53,
                                                "tenKhoaChiDinh": "Khoa Gây Mê Hồi Sức",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 216,
                                                "tenDonViTinh": "cái",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 22,
                                                "nhomDichVuCap2Id": null,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Vật tư y tế",
                                                "tenNhomDichVuCap2": null,
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": null,
                                                "trangThaiXuatKho": "Hoàn thành",
                                                "loaiNhapXuat": "NB tủ trực",
                                                "sttBangKe": 9,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": null,
                                                "maPhongThucHien": null,
                                                "tenPhongThucHien": null,
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": null,
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": 33453,
                                                "soPhieuId": null,
                                                "soKetNoi": null,
                                                "thanhToanSau": null,
                                                "kyThuatCao": true,
                                                "stent2": false,
                                                "thoiGianYLenh": null,
                                                "bacSiKhamId": null,
                                                "tenBacSiKham": null,
                                                "noiTru": true,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 3000000,
                                                "tongTienBh": 3000000
                                            },
                                            {
                                                "id": 353217,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Điều trị nội trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": null,
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "vtktc1",
                                                "tenDichVu": "Vật tư ktc 1",
                                                "dichVuId": 18952,
                                                "loaiDichVu": "Vật tư",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T11:00:24+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:59:25+07:00",
                                                "giaKhongBaoHiem": 20400000,
                                                "giaBaoHiem": 20000000,
                                                "giaPhuThu": 0,
                                                "tyLeBhTt": 100,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 0,
                                                "tienNbPhuThu": 0,
                                                "tienNbCungChiTra": 1000000,
                                                "tienBhThanhToan": 19000000,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 1000000,
                                                "tongTien": 20000000,
                                                "tienNb": 1000000,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 353215,
                                                "chiDinhTuLoaiDichVu": "Phẫu thuật - Thủ thuật",
                                                "khoaChiDinhId": 53,
                                                "tenKhoaChiDinh": "Khoa Gây Mê Hồi Sức",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 216,
                                                "tenDonViTinh": "cái",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 22,
                                                "nhomDichVuCap2Id": null,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Vật tư y tế",
                                                "tenNhomDichVuCap2": null,
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": null,
                                                "trangThaiXuatKho": "Hoàn thành",
                                                "loaiNhapXuat": "NB tủ trực",
                                                "sttBangKe": 9,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": null,
                                                "maPhongThucHien": null,
                                                "tenPhongThucHien": null,
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": null,
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": 33453,
                                                "soPhieuId": null,
                                                "soKetNoi": null,
                                                "thanhToanSau": null,
                                                "kyThuatCao": true,
                                                "stent2": false,
                                                "thoiGianYLenh": null,
                                                "bacSiKhamId": null,
                                                "tenBacSiKham": null,
                                                "noiTru": true,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 20000000,
                                                "tongTienBh": 20000000
                                            },
                                            {
                                                "id": 353297,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Điều trị nội trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": null,
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "st2",
                                                "tenDichVu": "Stent 2",
                                                "dichVuId": 18502,
                                                "loaiDichVu": "Vật tư",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T13:22:00+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:59:25+07:00",
                                                "giaKhongBaoHiem": 34680000,
                                                "giaBaoHiem": 34000000,
                                                "giaPhuThu": 0,
                                                "tyLeBhTt": 100,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 0,
                                                "tienNbPhuThu": 0,
                                                "tienNbCungChiTra": 1700000,
                                                "tienBhThanhToan": 32300000,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 1700000,
                                                "tongTien": 34000000,
                                                "tienNb": 1700000,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 353215,
                                                "chiDinhTuLoaiDichVu": "Phẫu thuật - Thủ thuật",
                                                "khoaChiDinhId": 53,
                                                "tenKhoaChiDinh": "Khoa Gây Mê Hồi Sức",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 216,
                                                "tenDonViTinh": "cái",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 22,
                                                "nhomDichVuCap2Id": null,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Vật tư y tế",
                                                "tenNhomDichVuCap2": null,
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": null,
                                                "trangThaiXuatKho": "Hoàn thành",
                                                "loaiNhapXuat": "NB tủ trực",
                                                "sttBangKe": 9,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": null,
                                                "maPhongThucHien": null,
                                                "tenPhongThucHien": null,
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": null,
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": 33453,
                                                "soPhieuId": null,
                                                "soKetNoi": null,
                                                "thanhToanSau": null,
                                                "kyThuatCao": true,
                                                "stent2": false,
                                                "thoiGianYLenh": null,
                                                "bacSiKhamId": null,
                                                "tenBacSiKham": null,
                                                "noiTru": true,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 34000000,
                                                "tongTienBh": 34000000
                                            }
                                        ],
                                        "tenNhomVatTuKtc": "Gói vật tư y tế kỹ thuật cao",
                                        "tienBhThanhToan": 54150000,
                                        "tongTien": 57000000,
                                        "tienNbTuTra": 0,
                                        "tienNb": 2850000,
                                        "tongTienBh": 57000000,
                                        "tienNbCungChiTra": 2850000,
                                        "tienMienGiam": 0
                                    },
                                    {
                                        "tienNguonKhac": 0,
                                        "dv": [
                                            {
                                                "id": 353298,
                                                "nbDotDieuTriId": 118906,
                                                "nbThongTinId": 116356,
                                                "tenNb": "LÊ HUY BÌNH",
                                                "maNb": "2210009626",
                                                "maHoSo": "2210310015",
                                                "maTheBhyt": "HT3380197006614",
                                                "tuNgayTheBhyt": "2022-07-01",
                                                "denNgayTheBhyt": "2022-11-02",
                                                "mucHuongBhyt": 95,
                                                "doiTuong": "Bảo hiểm",
                                                "doiTuongKcb": "Điều trị nội trú",
                                                "cdSoBo": null,
                                                "dsCdChinhId": null,
                                                "dsCdChinh": null,
                                                "dsCdKemTheoId": null,
                                                "dsCdKemTheo": null,
                                                "maDichVu": "st1",
                                                "tenDichVu": "Stent 1",
                                                "dichVuId": 18452,
                                                "loaiDichVu": "Vật tư",
                                                "soLuong": 1,
                                                "thoiGianChiDinh": "2022-10-31T13:22:00+07:00",
                                                "thoiGianThucHien": "2022-10-31T10:59:25+07:00",
                                                "giaKhongBaoHiem": 36720000,
                                                "giaBaoHiem": 36000000,
                                                "giaPhuThu": 0,
                                                "tyLeBhTt": 50,
                                                "tyLeTtDv": 100,
                                                "tuTra": false,
                                                "tienNbTuTra": 18000000,
                                                "tienNbPhuThu": 0,
                                                "tienNbCungChiTra": 900000,
                                                "tienBhThanhToan": 17100000,
                                                "tienNguonKhac": 0,
                                                "tienMienGiamPhieuThuBh": 0,
                                                "tienMienGiamPhieuThuKhongBh": 0,
                                                "tienMienGiamPhieuThu": 0,
                                                "phanTramMienGiamDichVuBh": 0,
                                                "phanTramMienGiamDichVuKhongBh": 0,
                                                "phanTramMienGiamDichVu": 0,
                                                "tienMienGiamDichVuBh": 0,
                                                "tienMienGiamDichVuKhongBh": 0,
                                                "tienMienGiamDichVu": 0,
                                                "tienGiamGiaBh": 0,
                                                "tienGiamGiaKhongBh": 0,
                                                "tienGiamGia": 0,
                                                "tienMienGiamBh": 0,
                                                "tienMienGiamKhongBh": 0,
                                                "tienMienGiam": 0,
                                                "thanhTien": 18900000,
                                                "tongTien": 36000000,
                                                "tienNb": 18900000,
                                                "thanhToan": false,
                                                "phatHanhHoaDon": false,
                                                "phieuThuId": 117458,
                                                "phieuDoiTraId": null,
                                                "soPhieuThu": null,
                                                "chiDinhTuDichVuId": 353215,
                                                "chiDinhTuLoaiDichVu": "Phẫu thuật - Thủ thuật",
                                                "khoaChiDinhId": 53,
                                                "tenKhoaChiDinh": "Khoa Gây Mê Hồi Sức",
                                                "bacSiChiDinhId": 14,
                                                "tenBacSiChiDinh": "Phạm Văn Minh",
                                                "donViTinhId": 216,
                                                "tenDonViTinh": "cái",
                                                "mucDichId": null,
                                                "tenMucDich": null,
                                                "khongTinhTien": false,
                                                "khongThuTien": false,
                                                "trangThaiHoan": "Thường",
                                                "loaiHinhThanhToanId": null,
                                                "tenLoaiHinhThanhToan": null,
                                                "nhomDichVuCap1Id": 22,
                                                "nhomDichVuCap2Id": null,
                                                "nhomDichVuCap3Id": null,
                                                "tenNhomDichVuCap1": "Vật tư y tế",
                                                "tenNhomDichVuCap2": null,
                                                "tenNhomDichVuCap3": null,
                                                "ghiChu": null,
                                                "donViYTeId": null,
                                                "coSoYTeId": null,
                                                "nbTheBaoHiemId": 45452,
                                                "trangThai": null,
                                                "trangThaiXuatKho": "Hoàn thành",
                                                "loaiNhapXuat": "NB tủ trực",
                                                "sttBangKe": 9,
                                                "maBacSiChiDinh": "minhpv",
                                                "phongThucHienId": null,
                                                "maPhongThucHien": null,
                                                "tenPhongThucHien": null,
                                                "nbBoChiDinhId": null,
                                                "ketQua": null,
                                                "ketLuan": null,
                                                "huongDieuTri": null,
                                                "loaiKetQua": null,
                                                "nbGoiDvId": null,
                                                "nbGoiPtTtId": null,
                                                "nbChuyenKhoaId": 33453,
                                                "soPhieuId": null,
                                                "soKetNoi": null,
                                                "thanhToanSau": null,
                                                "kyThuatCao": true,
                                                "stent2": true,
                                                "thoiGianYLenh": null,
                                                "bacSiKhamId": null,
                                                "tenBacSiKham": null,
                                                "noiTru": true,
                                                "cdChinh": null,
                                                "cdKemTheo": null,
                                                "dsCdVaoVien": null,
                                                "dsCdVaoVienId": null,
                                                "dsCdVaoVienKemTheoId": null,
                                                "dsCdRaVienId": null,
                                                "dsCdRaVien": null,
                                                "dsCdVaoVienKemTheo": null,
                                                "donGia": 36000000,
                                                "tongTienBh": 36000000
                                            }
                                        ],
                                        "tenNhomVatTuKtc": "Stent thứ 2",
                                        "tienBhThanhToan": 17100000,
                                        "tongTien": 36000000,
                                        "tienNbTuTra": 18000000,
                                        "tienNb": 18900000,
                                        "tongTienBh": 36000000,
                                        "tienNbCungChiTra": 900000,
                                        "tienMienGiam": 0
                                    }
                                ],
                                "tienBhThanhToan": 71250000,
                                "tongTien": 93000000,
                                "tienNbTuTra": 18000000,
                                "tienNb": 21750000,
                                "tongTienBh": 93000000,
                                "tienNbCungChiTra": 3750000,
                                "tienMienGiam": 0
                            }
                        ],
                        "tienNb": 21750000,
                        "tongTienBh": 93000000,
                        "tenNhomDichVuCap1": "10. Gói vật tư y tế",
                        "tienNbCungChiTra": 3750000,
                        "tienMienGiam": 0
                    }
                ],
                "tienNbCungChiTra": 3750000,
                "tienMienGiam": 0
            }
        ],
        "mucHuongBhyt": 95,
        "tienNbCungChiTra": 4252031,
        "tienMienGiam": 0,
        "tienNguonKhac": 0,
        "tienBhThanhToan": 80788589,
        "tongTien": 113042540,
        "maTheBhyt": "HT3380197006614",
        "tuNgayTheBhyt": "2022-07-01",
        "tienNb": 32253951,
        "tongTienBh": 103042540
    }
]