import { NHOM_DANH_MUC, NHOM_BAO_CAO, ROLES } from "constants/index";
// import { useTranslation } from "react-i18next";

// const { t } = useTranslation();

export const ListContentLeftHome = [
  {
    title: "Danh mục",
    bg: require("assets/images/pagehome/bgDanhMuc.png"),
    icon: require("assets/images/pagehome/icDanhMuc.png"),
    link: "/danh-muc",
    accessRoles: [ROLES["HE_THONG"].DANH_MUC],
  },
  {
    title: "Tiếp đón",
    bg: require("assets/images/pagehome/bgTiepDon.png"),
    icon: require("assets/images/pagehome/icTiepDon.png"),
    link: "/quan-ly-tiep-don",
    accessRoles: [ROLES["HE_THONG"].TIEP_DON],
  },
  {
    title: "Nhà thuốc",
    bg: require("assets/images/pagehome/bgNhaThuoc.png"),
    icon: require("assets/images/pagehome/icNhaThuoc.png"),
    link: "/quan-ly-nha-thuoc",
    accessRoles: [ROLES["HE_THONG"].NHA_THUOC],
  },
  {
    title: "Xét nghiệm",
    bg: require("assets/images/pagehome/bgXetNghiem.png"),
    icon: require("assets/images/pagehome/icXetNghiem.png"),
    link: "/xet-nghiem",
    accessRoles: [ROLES["HE_THONG"].XET_NGHIEM],
  },
  {
    title: "Khám bệnh",
    bg: require("assets/images/pagehome/bgTheoDoiDieuTri.png"),
    icon: require("assets/images/pagehome/icKhamBenh.png"),
    link: "/kham-benh",
    accessRoles: [ROLES["HE_THONG"].KHAM_BENH],
  },
  {
    title: "Thu ngân",
    bg: require("assets/images/pagehome/bgThuNgan.png"),
    icon: require("assets/images/pagehome/icThuNgan.png"),
    link: "/thu-ngan",
    accessRoles: [ROLES["HE_THONG"].THU_NGAN],
  },
  {
    title: "Thiết lập",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    icon: require("assets/images/pagehome/icThietLap.png"),
    link: "/thiet-lap",
    accessRoles: [ROLES["HE_THONG"].THIET_LAP],
  },
  {
    title: "Quản trị hệ thống",
    bg: require("assets/images/pagehome/bgQuanTriHeThong.png"),
    icon: require("assets/images/pagehome/icQuanTriHeThong.png"),
    link: "/quan-tri",
    accessRoles: [ROLES["HE_THONG"].QUAN_TRI_HE_THONG],
  },
  {
    title: "Quản lý thông báo",
    bg: require("assets/images/pagehome/bgQuanLyThongBao.png"),
    icon: require("assets/images/pagehome/icThongBao.png"),
    link: "/quan-ly-thong-bao",
    accessRoles: [ROLES["HE_THONG"].QUAN_LY_THONG_BAO],
  },
  {
    title: "Chẩn đoán hình ảnh và thăm dò chức năng",
    bg: require("assets/images/pagehome/bgChanDoanHinhAnh.png"),
    icon: require("assets/images/pagehome/icCDHA.png"),
    link: "/chan-doan-hinh-anh",
    accessRoles: [ROLES["HE_THONG"].CDHA_TDCN],
  },
  {
    title: "Kho",
    bg: require("assets/images/pagehome/bgKho.png"),
    icon: require("assets/images/pagehome/icKho.png"),
    link: "/kho",
    accessRoles: [ROLES["HE_THONG"].KHO],
  },
  {
    title: "Hồ sơ bệnh án",
    bg: require("assets/images/pagehome/bgHoSoBenhAn.png"),
    icon: require("assets/images/pagehome/icHoSoBenhAn.png"),
    link: "/ho-so-benh-an",
    accessRoles: [ROLES["HE_THONG"].HO_SO_BENH_AN],
  },
  {
    title: "Theo dõi điều trị",
    bg: require("assets/images/pagehome/bgTheoDoiDieuTri.png"),
    icon: require("assets/images/pagehome/icTheoDoiDieuTri.png"),
    link: "/theo-doi-nguoi-benh",
    accessRoles: [ROLES["HE_THONG"].THEO_DOI_DIEU_TRI],
  },
  {
    title: "Ký số",
    bg: require("assets/images/pagehome/bgKySo.png"),
    icon: require("assets/images/pagehome/icKySo.png"),
    link: "/ky-so",
    accessRoles: [ROLES["HE_THONG"].KY_SO],
  },
  {
    title: "Báo cáo",
    bg: require("assets/images/pagehome/bgBaoCao.png"),
    icon: require("assets/images/pagehome/icBaoCao.png"),
    link: "/bao-cao",
    accessRoles: [ROLES["HE_THONG"].BAO_CAO],
  },
  {
    title: "Quyết toán BHYT",
    bg: require("assets/images/pagehome/bgQuyetToanBHYT.png"),
    icon: require("assets/images/pagehome/icQuyetToanBHYT.png"),
    link: "/quyet-toan-bhyt",
    accessRoles: [ROLES["HE_THONG"].QUYET_TOAN_BHYT],
  },
  {
    title: "Quản lý nội trú",
    bg: require("assets/images/pagehome/bgQuanLyNoiTru.png"),
    icon: require("assets/images/pagehome/icQuanLyNoiTru.png"),
    link: "/quan-ly-noi-tru",
    accessRoles: [ROLES["HE_THONG"].QUAN_LY_NOI_TRU],
  },
  {
    title: "Khám sức khoẻ hợp đồng",
    bg: require("assets/images/pagehome/bgKskHopDong.png"),
    icon: require("assets/images/pagehome/icKskHopDong.png"),
    link: "/kham-suc-khoe",
    accessRoles: [ROLES["HE_THONG"].KHAM_SUC_KHOE],
  },
  {
    title: "Gói dịch vụ",
    bg: require("assets/images/pagehome/bgKskHopDong.png"),
    icon: require("assets/images/pagehome/icKskHopDong.png"),
    link: "/goi-dich-vu",
    accessRoles: [ROLES["HE_THONG"].GOI_DICH_VU],
  },
  {
    title: "Quản lý phẫu thuật - thủ thuật",
    bg: require("assets/images/pagehome/bgKskHopDong.png"),
    icon: require("assets/images/pagehome/icKskHopDong.png"),
    link: "/phau-thuat-thu-thuat",
    accessRoles: [ROLES["HE_THONG"].PHAU_THUAT_THU_THUAT],
  },
  {
    title: "Danh sách giấy đẩy cổng",
    bg: require("assets/images/pagehome/bgKskHopDong.png"),
    icon: require("assets/images/pagehome/icKskHopDong.png"),
    link: "/danh-sach-giay-day-cong",
    accessRoles: [ROLES["HE_THONG"].GIAY_DAY_CONG],
  },
  {
    title: "Sinh hiệu",
    bg: require("assets/images/pagehome/bgKskHopDong.png"),
    icon: require("assets/images/pagehome/icKskHopDong.png"),
    link: "/quan-ly-sinh-hieu",
    accessRoles: [ROLES["HE_THONG"].KHAM_SUC_KHOE],
  },
  {
    title: "Dashboard",
    bg: require("assets/images/pagehome/bgDashboard.png"),
    icon: require("assets/images/pagehome/icDashboard.png"),
    link: "/dashboard",
    accessRoles: [ROLES["HE_THONG"].BAO_CAO],
  },
];

export const ListContentLeftFunc = [
  {
    title: "Danh mục Loại cấp cứu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loai-cap-cuu",
    accessRoles: [ROLES["DANH_MUC"].LOAI_CC],
    group: NHOM_DANH_MUC.CAP_CUU,
  },
  {
    title: "Danh mục Thời gian cấp cứu",
    bg: require("assets/images/pagehome/icChucNang2.png"),
    link: "/danh-muc/thoi-gian-cap-cuu",
    accessRoles: [ROLES["DANH_MUC"].TG_CC],
    group: NHOM_DANH_MUC.CAP_CUU,
  },
  {
    title: "Danh mục nhãn áp",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuc-nang",
    group: NHOM_DANH_MUC.CHUYEN_KHOA_MAT,
  },
  {
    title: "Danh mục thị lực",
    bg: require("assets/images/pagehome/icChucNang2.png"),
    link: "/danh-muc/chuc-nang",
    group: NHOM_DANH_MUC.CHUYEN_KHOA_MAT,
  },
  {
    title: "Danh mục đơn vị Axis",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuc-nang",
    group: NHOM_DANH_MUC.CHUYEN_KHOA_MAT,
  },
  {
    title: "Danh mục đơn vị CYL",
    bg: require("assets/images/pagehome/icChucNang2.png"),
    link: "/danh-muc/chuc-nang",
    group: NHOM_DANH_MUC.CHUYEN_KHOA_MAT,
  },
  {
    title: "Danh mục đơn vị SPH",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuc-nang",
    group: NHOM_DANH_MUC.CHUYEN_KHOA_MAT,
  },
  {
    title: "Danh mục quầy tiếp đón",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/quay-tiep-don",
    accessRoles: [ROLES["DANH_MUC"].QUAY],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục phương thức thanh toán",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phuong-thuc-thanh-toan",
    accessRoles: [ROLES["DANH_MUC"].PTTT],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục bệnh viện",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/benh-vien",
    accessRoles: [ROLES["DANH_MUC"].BENH_VIEN],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục nguyên nhân tai nạn thương tích",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nguyen-nhan-nhap-vien",
    accessRoles: [ROLES["DANH_MUC"].NGUYEN_NHAN_NHAP_VIEN],
    group: NHOM_DANH_MUC.CAP_CUU,
  },
  {
    title: "Danh mục chức vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuc-vu",
    accessRoles: [ROLES["DANH_MUC"].CHUC_VU],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục nghề nghiệp",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nghe-nghiep",
    accessRoles: [ROLES["DANH_MUC"].NGHE_NGHIEP],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục mối quan hệ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/moi-quan-he",
    accessRoles: [ROLES["DANH_MUC"].MOI_QUAN_HE],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục khoa",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/khoa",
    accessRoles: [ROLES["DANH_MUC"].KHOA],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục phòng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phong",
    accessRoles: [ROLES["DANH_MUC"].PHONG],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục dịch vụ khám bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dich-vu-kham-benh",
    accessRoles: [ROLES["DANH_MUC"].DICH_VU_KHAM_BENH],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục chuyên khoa",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuyen-khoa",
    accessRoles: [ROLES["DANH_MUC"].CHUYEN_KHOA],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục vị trí chấn thương",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/vi-tri-chan-thuong",
    accessRoles: [ROLES["DANH_MUC"].VI_TRI_CHAN_THUONG],
    group: NHOM_DANH_MUC.CAP_CUU,
  },
  {
    title: "Danh mục Thẻ bảo hiểm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/the-bao-hiem",
    accessRoles: [ROLES["DANH_MUC"].THE_BAO_HIEM],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Gói mổ 10 ngày",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/goi-pt-tt",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Học hàm học vị",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/hoc-ham-hoc-vi",
    accessRoles: [ROLES["DANH_MUC"].HOC_HAM],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục Dân tộc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dan-toc",
    accessRoles: [ROLES["DANH_MUC"].DAN_TOC],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục Loa gọi số",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loa-goi-so",
    accessRoles: [ROLES["DANH_MUC"].LOA_GOI_SO],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Tòa nhà",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/toa-nha",
    accessRoles: [ROLES["DANH_MUC"].NHA],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục nhóm chi phí",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-chi-phi",
    accessRoles: [ROLES["DANH_MUC"].NHOM_CHI_PHI],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục loại bữa ăn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loai-bua-an",
    accessRoles: [ROLES["DANH_MUC"].LOAI_BUA_AN],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Lý do tạm ứng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/ly-do-tam-ung",
    accessRoles: [ROLES["DANH_MUC"].LY_DO_TAM_UNG],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục mẫu diễn biến",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/mau-dien-bien",
    accessRoles: [ROLES["DANH_MUC"].MAU_DIEN_BIEN],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Văn bằng chuyên môn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/van-bang-chuyen-mon",
    accessRoles: [ROLES["DANH_MUC"].VAN_BANG],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục Đường dùng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/duong-dung",
    accessRoles: [ROLES["DANH_MUC"].DUONG_DUNG],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Liều dùng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/lieu-dung",
    accessRoles: [ROLES["DANH_MUC"].LIEU_DUNG],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục mã máy",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/ma-may",
    accessRoles: [ROLES["DANH_MUC"].MA_MAY],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục hoạt chất",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/hoat-chat",
    accessRoles: [ROLES["DANH_MUC"].HOAT_CHAT],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục người đại diện",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nguoi-dai-dien",
    accessRoles: [ROLES["DANH_MUC"].NGUOI_DAI_DIEN],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục cơ quan đơn vị",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/co-quan-don-vi",
    accessRoles: [ROLES["DANH_MUC"].CO_QUAN],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục quân hàm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/quan-ham",
    accessRoles: [ROLES["DANH_MUC"].QUAN_HAM],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục đơn vị chi nhánh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/don-vi-chi-nhanh",
    accessRoles: [],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục lời dặn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loi-dan",
    accessRoles: [ROLES["DANH_MUC"].LOI_DAN],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Đối tác",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/doi-tac",
    accessRoles: [ROLES["DANH_MUC"].NHA_SAN_XUAT],
    group: NHOM_DANH_MUC.KHO,
  },
  // {
  //   title: "Danh mục Đối tác",
  //   bg: require("assets/images/pagehome/icChucNang1.png"),
  //   link: "/danh-muc/doi-tac",
  //   accessRoles: [ROLES["DANH_MUC"].DOI_TAC],
  //   group: NHOM_DANH_MUC.HANH_CHINH,
  // },
  {
    title: "Danh mục Lý do đổi trả dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/ly-do-tra-dv",
    accessRoles: [ROLES["DANH_MUC"].DOI_TRA_DICH_VU],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Bệnh phẩm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/benh-pham",
    accessRoles: [ROLES["DANH_MUC"].BENH_PHAM],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Phương pháp gây mê",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phuong-phap-gay-me",
    accessRoles: [ROLES["DANH_MUC"].PHUONG_PHAP_GAY_ME],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Phương pháp nhuộm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phuong-phap-nhuom",
    accessRoles: [ROLES["DANH_MUC"].PHUONG_PHAP_NHUOM],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Vị trí sinh thiết",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/vi-tri-sinh-thiet",
    accessRoles: [ROLES["DANH_MUC"].VI_TRI_SINH_THIET],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục dịch vụ ăn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dich-vu-an",
    accessRoles: [ROLES["DANH_MUC"].DICH_VU_AN],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Định mức thặng số bán lẻ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/thang-so-ban-le",
    accessRoles: [ROLES["DANH_MUC"].DINH_MUC_THANG_SO],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Tài sản khác",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuc-nang",
    accessRoles: [ROLES["DANH_MUC"].TAI_SAN_KHAC],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Loại đối tượng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loai-doi-tuong",
    accessRoles: [ROLES["DANH_MUC"].LOAI_DOI_TUONG],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Loại Bệnh Án",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loai-benh-an",
    accessRoles: [ROLES["DANH_MUC"].LOAI_BA],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Nhóm vật tư",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-vat-tu",
    accessRoles: [ROLES["DANH_MUC"].NHOM_VAT_TU],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Nhóm hóa chất",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-hoa-chat",
    accessRoles: [ROLES["DANH_MUC"].NHOM_HOA_CHAT],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Dịch vụ Chẩn đoán hình ảnh và thăm dò chức năng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dich-vu-cdha-tdcn",
    accessRoles: [ROLES["DANH_MUC"].CDHA_TDCN],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Vật tư",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/vat-tu",
    accessRoles: [ROLES["DANH_MUC"].VAT_TU],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Dịch vụ xét nghiệm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dich-vu-xet-nghiem",
    accessRoles: [ROLES["DANH_MUC"].DICH_VU_XN],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Hóa chất",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/hoa-chat",
    accessRoles: [ROLES["DANH_MUC"].HOA_CHAT],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/thuoc",
    accessRoles: [ROLES["DANH_MUC"].THUOC],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Dịch vụ Phẫu thuật - Thủ thuật",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dich-vu-phau-thuat",
    accessRoles: [ROLES["DANH_MUC"].DV_PHAU_THUAT_THU_THUAT],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Chế phẩm máu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/che-pham-mau",
    accessRoles: [ROLES["DANH_MUC"].CHE_PHAM_MAU],
    group: NHOM_DANH_MUC.KHO,
  },
  // {
  //   title: "Danh mục Dịch vụ ngoài điều trị",
  //   bg: require("assets/images/pagehome/icChucNang1.png"),
  //   link: "/danh-muc/chuc-nang",
  //   group: NHOM_DANH_MUC.DICH_VU,
  // },
  {
    title: "Danh mục Dịch vụ ngoài điều trị",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/ngoai-dieu-tri",
    group: NHOM_DANH_MUC.DICH_VU,
    accessRoles: [ROLES["DANH_MUC"].DV_NGOAI_DIEU_TRI],
  },

  {
    title: "Danh mục nhóm dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-dich-vu",
    accessRoles: [ROLES["DANH_MUC"].NHOM_DICH_VU],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Đơn vị tính",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/don-vi-tinh",
    accessRoles: [ROLES["DANH_MUC"].DON_VI_TINH],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Nhóm thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-thuoc",
    accessRoles: [ROLES["DANH_MUC"].NHOM_THUOC],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Phân loại thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phan-loai-thuoc",
    accessRoles: [ROLES["DANH_MUC"].PHAN_LOAI_THUOC],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Phân nhóm thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phan-nhom-thuoc",
    accessRoles: [ROLES["DANH_MUC"].PHAN_NHOM_THUOC],
    group: NHOM_DANH_MUC.KHO,
  },
  // {
  //   title: "Danh mục Gói dịch vụ",
  //   bg: require("assets/images/pagehome/icChucNang1.png"),
  //   link: "/danh-muc/goi-dich-vu",
  //   accessRoles: [ROLES["DANH_MUC"].GOI_DICH_VU],
  //   group: NHOM_DANH_MUC.DICH_VU,
  // },
  {
    title: "Danh mục địa chỉ hành chính",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dia-chi-hanh-chinh",
    accessRoles: [ROLES["DANH_MUC"].DIA_CHI_HANH_CHINH],
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục nhóm bệnh tật",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-benh-tat",
    accessRoles: [ROLES["DANH_MUC"].BENH_TAT],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục máy in",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/may-in",
    accessRoles: [ROLES["DANH_MUC"].MAY_IN],
    group: NHOM_DANH_MUC.KY_IN_PHIEU,
  },
  {
    title: "Danh mục báo cáo",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/bao-cao",
    accessRoles: [ROLES["DANH_MUC"].BAO_CAO],
    group: NHOM_DANH_MUC.KY_IN_PHIEU,
  },
  {
    title: "Danh mục mẫu kết quả xét nghiệm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/mau-ket-qua-xet-nghiem",
    accessRoles: [ROLES["DANH_MUC"].MAU_KET_QUA_XN],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Nơi lấy mẫu bệnh phẩm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/noi-lay-benh-pham",
    accessRoles: [ROLES["DANH_MUC"].NOI_LAY_BENH_PHAM],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Hình thức nhập/Loại xuất",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/hinh-thuc-nhap-xuat",
    accessRoles: [ROLES["DANH_MUC"].HINH_THUC_NHAP_XUAT_LOAI_XUAT],
    group: NHOM_DANH_MUC.KHO,
  },

  {
    title: "Danh mục Nguồn nhập kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nguon-nhap-kho",
    accessRoles: [ROLES["DANH_MUC"].NGUON_NHAP_KHO],
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục Bộ chỉ định",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/bo-chi-dinh",
    accessRoles: [ROLES["DANH_MUC"].BO_CHI_DINH],
    group: NHOM_DANH_MUC.DICH_VU,
  },

  {
    title: "Danh mục Chương trình giảm giá",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chuong-trinh-giam-gia",
    accessRoles: [ROLES["DANH_MUC"].CHUONG_TRINH_GIAM_GIA],
    group: NHOM_DANH_MUC.KHACH_HANG,
  },
  {
    title: "Danh mục Nguồn người bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nguon-nguoi-benh",
    accessRoles: [ROLES["DANH_MUC"].NGUON_NGUOI_BENH],
    group: NHOM_DANH_MUC.KHACH_HANG,
  },
  {
    title: "Danh mục Hạng Thẻ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/hang-the",
    accessRoles: [ROLES["DANH_MUC"].HANG_THE],
    group: NHOM_DANH_MUC.KHACH_HANG,
  },
  {
    title: "Danh mục Xuất xứ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/xuat-xu",
    accessRoles: [ROLES["DANH_MUC"].XUAT_XU],
    group: NHOM_DANH_MUC.KHO,
  },
  // thieu mo ta
  {
    title: "Danh mục mẫu kết quả chẩn đoán hình ảnh và thăm dò chức năng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/mau-ket-qua-cls",
    accessRoles: [ROLES["DANH_MUC"].MAU_KQ_CDHA_TDCN],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Nhóm chỉ số",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/nhom-chi-so",
    accessRoles: [ROLES["DANH_MUC"].NHOM_CHI_SO],
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục Quyền ký",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/quyen-ky",
    accessRoles: [ROLES["DANH_MUC"].QUYEN_KY],
    group: NHOM_DANH_MUC.KY_IN_PHIEU,
  },
  {
    title: "Danh mục Loại phiếu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loai-phieu",
    group: NHOM_DANH_MUC.KY_IN_PHIEU,
    accessRoles: [ROLES["DANH_MUC"].LOAI_PHIEU],
  },
  {
    title: "Danh mục mẫu QMS",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/mau-qms",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["DANH_MUC"].MAU_QMS],
  },
  {
    title: "Danh mục Thuốc kê ngoài",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/thuoc-ke-ngoai",
    group: NHOM_DANH_MUC.KHO,
    accessRoles: [ROLES["DANH_MUC"].THUOC_KE_NGOAI],
  },
  {
    title: "Danh mục Liều dùng - Bác sĩ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/lieu-dung-bac-si",
    group: NHOM_DANH_MUC.KHO,
    accessRoles: [ROLES["DANH_MUC"].LIEU_DUNG_BS],
  },
  {
    title: "Danh mục kiosk",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/kiosk",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["THIET_LAP"].KIOSK],
  },
  {
    title: "Danh mục Tài liệu hướng dẫn sử dụng",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/huong-dan-su-dung",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["DANH_MUC"].HDSD],
  },
  {
    title: "Danh mục Hội đồng",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/hoi-dong",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["DANH_MUC"].HOI_DONG],
  },
  {
    title: "Danh mục Loại giường",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/loai-giuong",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [],
  },
  {
    title: "Danh mục Số hiệu giường",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/so-hieu-giuong",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [],
  },
  {
    title: "Danh mục Dịch vụ giường",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/dich-vu-giuong",
    group: NHOM_DANH_MUC.DICH_VU,
    accessRoles: [],
  },
  {
    title: "Danh mục bác sĩ ngoại viện",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/bac-si-ngoai-vien",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["DANH_MUC"].BAC_SI_NGOAI_VIEN],
  },
  {
    title: "Danh mục chế độ chăm sóc",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/che-do-cham-soc",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["DANH_MUC"].CHE_DO_CHAM_SOC],
  },
  {
    title: "Danh mục mẫu kết quả phẫu thuật - thủ thuật",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/danh-muc/mau-kq-pt-tt",
    group: NHOM_DANH_MUC.CHUNG,
    accessRoles: [ROLES["DANH_MUC"].MAU_KQ_PT_TT],
  },
  {
    title: "Danh mục loại hình thanh toán",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/loai-hinh-thanh-toan",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Chỉ số sống",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chi-so-song",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Phân loại đánh giá BMI",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/phan-loai-bmi",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục Ngày nghỉ lễ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/ngay-nghi-le",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục hậu quả tương tác",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/hau-qua-tuong-tac",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục đặc tính dược lý",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/dac-tinh-duoc-ly",
    accessRoles: [ROLES["DANH_MUC"].DAC_TINH_DUOC_LY],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục mức độ tương tác",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/muc-do-tuong-tac",
    accessRoles: [],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Khai báo tương tác thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/tuong-tac-thuoc",
    accessRoles: [ROLES["DANH_MUC"].TUONG_TAC_THUOC],
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Chi phí hấp sấy VTYT tái sử dụng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/danh-muc/chi-phi-hap-say-vtyt-tai-su-dung",
    accessRoles: [ROLES["DANH_MUC"].CHI_PHI_HAP_SAY],
    group: NHOM_DANH_MUC.CHUNG,
  },
];

export const ListDanhMucXN = [
  {
    title: "Lấy mẫu bệnh phẩm",
    i18n: "xetNghiem.layMauBenhPham",
    bg: require("assets/images/pagehome/icLayMau.png"),
    link: "/xet-nghiem/lay-mau",
    accessRoles: [ROLES["XET_NGHIEM"].MH_LAY_MAU],
  },
  {
    title: "Thực hiện Sinh hóa- Huyết học",
    i18n: "xetNghiem.thucHienSinhHoaHuyetHoc",
    bg: require("assets/images/pagehome/bgXNSinhHoa.png"),
    link: "/xet-nghiem/sinh-hoa-huyet-hoc",
    accessRoles: [ROLES["XET_NGHIEM"].XET_NGHIEM_HH],
  },
  {
    title: "Thực hiện Giải phẫu bệnh- Vi sinh",
    i18n: "xetNghiem.thucHienGiaiPhauBenhViSinh",
    bg: require("assets/images/pagehome/icGPBVS.png"),
    link: "/xet-nghiem/giai-phau-benh-vi-ky-sinh",
    accessRoles: [ROLES["XET_NGHIEM"].XET_NGHIEM_GPB],
  },
];

export const ListDanhMucTN = [
  {
    title: "Danh sách phiếu thu",
    i18n: "thuNgan.danhSachPhieuThu",
    bg: require("assets/images/thuNgan/dsPhieuThu.png"),
    link: "/thu-ngan/danh-sach-phieu-thu",
    // accessRoles: [ROLES["THU_NGAN"].THU_NGAN],
  },
  {
    title: "DS phiếu yêu cầu hoàn",
    i18n: "thuNgan.danhSachPhieuYCH",
    bg: require("assets/images/thuNgan/dsPhieuHoan.png"),
    link: "/thu-ngan/ds-phieu-yeu-cau-hoan",
    // accessRoles: [ROLES["THU_NGAN"].DANH_SACH_PHIEU_THU],
  },
  {
    title: "DS hóa đơn điện tử",
    i18n: "thuNgan.danhSachHoaDonDienTu",
    bg: require("assets/images/thuNgan/dsPhieuHoan.png"),
    link: "/thu-ngan/ds-hoa-don-dien-tu",
    // accessRoles: [ROLES["THU_NGAN"].DANH_SACH_PHIEU_THU],
  },
  {
    title: "Quản lý tạm ứng",
    i18n: "thuNgan.quanLyTamUng.quanLyTamUng",
    bg: require("assets/images/thuNgan/dsPhieuHoan.png"),
    link: "/thu-ngan/quan-ly-tam-ung",
    accessRoles: [ROLES["THU_NGAN"].XEM_DS_NB_QUAN_LY_TAM_UNG],
  },
];

export const ListQuanTriHeThong = [
  {
    title: "Danh mục vai trò",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-tri/danh-muc-vai-tro",
    accessRoles: [ROLES["QUAN_LY_TAI_KHOAN"].VAI_TRO_HE_THONG],
  },
  {
    title: "Quản lý tài khoản",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/quan-tri/danh-muc-tai-khoan",
    accessRoles: [ROLES["QUAN_LY_TAI_KHOAN"].QUAN_LY_TAI_KHOAN],
  },
  {
    title: "Danh mục Nhân viên",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-tri/nhan-vien",
    accessRoles: [ROLES["QUAN_LY_TAI_KHOAN"].NHAN_VIEN],
  },
  {
    title: "Danh mục quyền",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-tri/quyen",
    accessRoles: [ROLES["QUAN_LY_TAI_KHOAN"].QUYEN],
  },
  {
    title: "Danh mục nhóm tính năng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-tri/nhom-tinh-nang",
    accessRoles: [ROLES["QUAN_LY_TAI_KHOAN"].NHOM_TINH_NANG],
  },
];

export const ListThietLap = [
  {
    title: "Thiết lập chung",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/thiet-lap-chung",
    accessRoles: [ROLES.THIET_LAP_CHUNG],
  },
  {
    title: "Tách gộp phiếu Xét nghiệm",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/tach-gop-phieu-xet-nghiem",
  },
  {
    title: "Tách gộp phiếu chỉ định DVKT",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/tach-gop-phieu-dvkt",
  },
  {
    title: "Thiết lập tích điểm",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/tich-diem",
  },
  {
    title: "Thiết lập thông số hàng đợi",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/thong-so-hang-doi",
  },
  {
    title: "Thiết lập phiếu tại các màn hình",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/thiet-lap-phieu-in",
  },
  {
    title: "Thiết lập phiếu lĩnh trả",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/thiet-lap/phieu-linh-tra",
  },
];

export const ListKho = [
  {
    title: "Thiết lập kho chỉ định",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/kho/thiet-lap-kho-chi-dinh",
  },
  {
    title: "Quản trị kho",
    bg: require("assets/images/pagehome/icQuanTriKho.png"),
    link: "/kho/quan-tri-kho",
  },
  {
    title: "Quản lý thầu",
    bg: require("assets/images/pagehome/icQuyetDinhThau.png"),
    link: "/kho/quan-ly-thau",
  },
  {
    title: "Nhập kho",
    bg: require("assets/images/pagehome/icNhapKho.png"),
    link: "/kho/nhap-kho",
  },
  {
    title: "Xuất kho",
    bg: require("assets/images/pagehome/icXuatKho.png"),
    link: "/kho/xuat-kho",
    accessRoles: [ROLES["KHO"].XEM_PHIEU_XUAT_KHO],
  },
  {
    title: "Danh sách tồn kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/kho/danh-sach-ton-kho",
  },
  {
    title: "Phát thuốc ngoại trú",
    bg: require("assets/images/pagehome/bgPhatThuocNgoaiTru.png"),
    link: "/kho/phat-thuoc-ngoai-tru",
  },
  {
    title: "Vật tư ký gửi",
    bg: require("assets/images/pagehome/bgPhatThuocNgoaiTru.png"),
    link: "/kho/vat-tu-ky-gui",
  },
];

export const ListChanDoanHinhAnh = [
  {
    title: "Chờ tiếp đón",
    i18n: "cdha.choTiepDon",
    bg: require("assets/images/pagehome/bgXNLayMau.png"),
    link: "/chan-doan-hinh-anh/cho-tiep-don",
    accessRoles: [ROLES["CHAN_DOAN_HINH_ANH"].CHO_TIEP_DON],
  },
  {
    title: "Tiếp nhận",
    i18n: "common.tiepNhan",
    bg: require("assets/images/pagehome/bgXNLayMau.png"),
    link: "/chan-doan-hinh-anh/tiep-nhan",
    accessRoles: [ROLES["CHAN_DOAN_HINH_ANH"].TIEP_NHAN],
  },
  // {
  //   title: "Đọc kết quả",
  //   bg: require("assets/images/pagehome/bgXNLayMau.png"),
  //   link: "/chan-doan-hinh-anh/doc-ket-qua",
  // },
  {
    title: "Biểu đồ thống kê",
    i18n: "cdha.bieuDoThongKe",
    bg: require("assets/images/pagehome/bgXNLayMau.png"),
    link: "/chan-doan-hinh-anh/bieu-do-thong-ke",
  },
  {
    title: "Chẩn đoán hình ảnh - Thăm dò chức năng",
    i18n: "cdha.cdhaTdcn",
    bg: require("assets/images/pagehome/bgXNLayMau.png"),
    link: "/chan-doan-hinh-anh/thuc-hien-cdha-tdcn",
  },
];

export const ListHoSoBenhAn = [
  {
    title: "Danh sách người bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/ho-so-benh-an/danh-sach-nguoi-benh",
  },
  {
    title: "Danh sách lưu trữ bệnh án",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/ho-so-benh-an/danh-sach-luu-tru-benh-an",
  },
];

export const ListPhieuTheoDoiDieuTri = [
  {
    title: "Danh sách người bệnh cần theo dõi",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/theo-doi-nguoi-benh/danh-sach-nguoi-benh",
  },
];

export const ListKySo = [
  {
    title: "Thiết lập quyền ký",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/ky-so/thiet-lap-quyen-ky",
  },
  {
    title: "Danh sách phiếu chờ ký",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/ky-so/danh-sach-phieu-cho-ky",
  },
  {
    title: "Lịch sử ký",
    bg: require("assets/images/pagehome/bgLichSuKy.png"),
    link: "/ky-so/lich-su-ky/danh-sach-nguoi-benh",
  },
];
export const ListQuyetToanBHYT = [
  {
    title: "Danh sách người bệnh chờ tạo hồ sơ quyết toán BHYT",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/quyet-toan-bhyt/danh-sach-nguoi-benh-cho-tao-ho-so-quyet-toan-bhyt",
  },
  {
    title: "Danh sách hồ sơ bảo hiểm (79A 46 cột theo QĐ4210)",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/quyet-toan-bhyt/danh-sach-ho-so-bao-hiem-79a-46cot-theo-qd4210",
  },
];

export const ListNhomDanhMuc = [
  // {
  //   title: "Danh mục chuyên khoa mắt",
  //   group: NHOM_DANH_MUC.CHUYEN_KHOA_MAT,
  // },
  {
    title: "Danh mục về cấp cứu",
    group: NHOM_DANH_MUC.CAP_CUU,
  },
  {
    title: "Danh mục về kho",
    group: NHOM_DANH_MUC.KHO,
  },
  {
    title: "Danh mục về ký_in_phiếu",
    group: NHOM_DANH_MUC.KY_IN_PHIEU,
  },
  {
    title: "Danh mục về dịch vụ",
    group: NHOM_DANH_MUC.DICH_VU,
  },
  {
    title: "Danh mục về TT hành chính",
    group: NHOM_DANH_MUC.HANH_CHINH,
  },
  {
    title: "Danh mục chung",
    group: NHOM_DANH_MUC.CHUNG,
  },
  {
    title: "Danh mục chăm sóc khách hàng",
    group: NHOM_DANH_MUC.KHACH_HANG,
  },
];

export const ListNhomBaoCao = [
  {
    title: "Báo cáo tài chính",
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
  },
  {
    title: "Báo cáo dịch vụ",
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
  },
  {
    title: "Báo cáo phòng khám",
    group: NHOM_BAO_CAO.BAO_CAO_PHONG_KHAM,
  },
  {
    title: "Báo cáo kho",
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
  },
  {
    title: "Báo cáo kho vật tư/ hóa chất",
    group: NHOM_BAO_CAO.BAO_CAO_KHO_VT_HC,
  },
  {
    title: "Báo cáo nhà thuốc",
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
  },
  {
    title: "Báo cáo khám sức khỏe",
    group: NHOM_BAO_CAO.BAO_CAO_KHAM_SUC_KHOE,
  },
  {
    title: "Báo cáo Gói liệu trình",
    group: NHOM_BAO_CAO.BAO_CAO_GOI_LIEU_TRINH,
  },
  {
    title: "Báo cáo kế hoạch tổng hợp",
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
  },
  {
    title: "Báo cáo phẫu thuật, thủ thuật",
    group: NHOM_BAO_CAO.BAO_CAO_PHAU_THUAT_THU_THUAT,
  },
];
export const ListBaoCao = [
  {
    title: "PK01. Danh sách người bệnh khám chi tiết",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/danh-sach-nguoi-benh-kham-chi-tiet",
    accessRoles: [ROLES["BAO_CAO"].NGUOI_BENH_KHAM_CHI_TIET],
    group: NHOM_BAO_CAO.BAO_CAO_PHONG_KHAM,
    capitalizeTitle: false,
  },
  {
    title: "PK02. Danh sách người bệnh có lịch hẹn khám",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/danh-sach-nguoi-benh-co-lich-hen-kham",
    accessRoles: [ROLES["BAO_CAO"].NGUOI_BENH_CO_LICH_HEN_KHAM],
    group: NHOM_BAO_CAO.BAO_CAO_PHONG_KHAM,
    capitalizeTitle: false,
  },
  {
    title: "PK03. Danh sách người bệnh bảo hiểm y tế",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/pk-03",
    accessRoles: [ROLES["BAO_CAO"].PK03],
    group: NHOM_BAO_CAO.BAO_CAO_PHONG_KHAM,
    capitalizeTitle: false,
  },
  {
    title: "BC01. Báo cáo chi tiết theo người bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-01",
    accessRoles: [ROLES["BAO_CAO"].BC01],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC02. Báo cáo chi tiết người bệnh đã tiếp đón",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/chi-tiet-nguoi-benh-da-tiep-don",
    accessRoles: [ROLES["BAO_CAO"].BC02],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC03. Thống kê số lượng người bệnh theo loại dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-03",
    accessRoles: [ROLES["BAO_CAO"].BC03],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC04. Thống kê số lượng dịch vụ theo đối tượng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-04",
    accessRoles: [ROLES["BAO_CAO"].BC04],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC05. Báo cáo chi tiết tiếp nhận dịch vụ theo phòng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-05",
    accessRoles: [ROLES["BAO_CAO"].BC05],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC06. Báo cáo chấm công thực hiện dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-06",
    accessRoles: [ROLES["BAO_CAO"].BC06],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC07. Báo cáo chấm công thực hiện dịch vụ yêu cầu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-07",
    accessRoles: [ROLES["BAO_CAO"].BC07],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC08. Báo cáo số lượng dịch vụ từ bệnh viện E",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-08",
    accessRoles: [ROLES["BAO_CAO"].BC08],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC09. Báo cáo thống kê dịch vụ theo NB",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-09",
    accessRoles: [ROLES["BAO_CAO"].BC09],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC10. Báo cáo chi tiết dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-10",
    accessRoles: [ROLES["BAO_CAO"].BC10],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "BC11. Báo cáo tổng hợp dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bc-11",
    accessRoles: [ROLES["BAO_CAO"].BC11],
    group: NHOM_BAO_CAO.BAO_CAO_DICH_VU,
    capitalizeTitle: false,
  },
  {
    title: "TC01. Báo cáo tổng hợp thu tiền người bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tong-hop-thu-tien-nb",
    accessRoles: [ROLES["BAO_CAO"].TONG_HOP_THU_TIEN_NB],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC02. Bảng tổng hợp chi tiết thu chi theo thu ngân",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tong-hop-chi-tiet-thu-chi-theo-thu-ngan",
    accessRoles: [ROLES["BAO_CAO"].TC02],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC03. Báo cáo sử dụng hóa đơn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc03",
    accessRoles: [ROLES["BAO_CAO"].TC03],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC04. Báo cáo chi tiết sử dụng hóa đơn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc-04",
    accessRoles: [ROLES["BAO_CAO"].TC04],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC05. Báo cáo thu tiền theo bác sĩ khám",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc05",
    accessRoles: [ROLES["BAO_CAO"].TC05],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title:
      "TC06. Tổng hợp chi phí khám bệnh, chữa bệnh của người tham gia bảo hiểm y tế",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc06",
    accessRoles: [ROLES["BAO_CAO"].TC06],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC07. Báo cáo thu tiền dịch vụ ngoại trú",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc07",
    accessRoles: [ROLES["BAO_CAO"].TC07],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC08. Báo cáo thu tiền dịch vụ theo yêu cầu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc08",
    accessRoles: [ROLES["BAO_CAO"].TC08],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC09. Báo cáo thu tiền theo loại tiền",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc09",
    accessRoles: [ROLES["BAO_CAO"].TC09],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC10. Tổng hợp doanh thu TNDN",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc10",
    accessRoles: [ROLES["BAO_CAO"].TC10],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC11. Báo cáo tổng hợp doanh số",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc11",
    accessRoles: [ROLES["BAO_CAO"].TC11],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title:
      "TC12. Theo dõi tình hình tạm ứng và chi phí điều trị của Người bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc12",
    accessRoles: [ROLES["BAO_CAO"].TC12],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC13. Báo cáo danh sách người bệnh tạm ứng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc13",
    accessRoles: [ROLES["BAO_CAO"].TC13],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC14. Báo cáo tổng hợp tiền tạm ứng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc14",
    accessRoles: [ROLES["BAO_CAO"].TC14],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC15. Báo cáo thu và hoàn tạm ứng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc15",
    accessRoles: [ROLES["BAO_CAO"].TC15],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC16. Báo cáo tạm ứng - hoàn ứng của NB",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc16",
    accessRoles: [ROLES["BAO_CAO"].TC16],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC17. Báo cáo theo dõi tình hình tạm ứng theo nhà thu ngân",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc17",
    accessRoles: [ROLES["BAO_CAO"].TC17],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC17.1. Báo cáo theo dõi tình hình tạm ứng trong tháng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc17.1",
    accessRoles: [ROLES["BAO_CAO"].TC17_1],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC18. Báo cáo số dư tạm ứng lũy kế",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc18",
    accessRoles: [ROLES["BAO_CAO"].TC18],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC20. Bảng chấm công các dịch vụ theo yêu cầu ngày thường",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc20",
    accessRoles: [ROLES["BAO_CAO"].TC20],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC20.1 Bảng chia tiền dịch vụ khám theo yêu cầu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc20.1",
    accessRoles: [ROLES["BAO_CAO"].TC20_1],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC21 Bảng tổng hợp thu dịch vụ KCB",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc21",
    accessRoles: [ROLES["BAO_CAO"].TC21],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC22 Bảng kê chi tiết thu dịch vụ KCB",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc22",
    accessRoles: [ROLES["BAO_CAO"].TC22],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC23 Bảng tổng hợp thu dịch vụ theo khoa thực hiện",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc23",
    accessRoles: [ROLES["BAO_CAO"].TC23],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "TC24 Phân tích cơ cấu thu chi theo khoa chỉ định",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/tc24",
    accessRoles: [ROLES["BAO_CAO"].TC24],
    group: NHOM_BAO_CAO.BAO_CAO_TAI_CHINH,
    capitalizeTitle: false,
  },
  {
    title: "K01. Bảng kê hóa đơn nhập",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/bang-ke-hoa-don-nhap",
    accessRoles: [ROLES["BAO_CAO"].BANG_KE_HOA_DON_NHAP],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K01.1. Bảng kê chi tiết nhập theo nhà cung cấp",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/nhap-theo-nha-cung-cap",
    accessRoles: [ROLES["BAO_CAO"].NHAP_THEO_NHA_CC],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K02. Báo cáo xuất nhập tồn kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k02",
    accessRoles: [ROLES["BAO_CAO"].XUAT_NHAP_TON_KHO],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K02.1. Báo cáo xuất nhập tồn kho lẻ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k02_1",
    accessRoles: [ROLES["BAO_CAO"].K02_1],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K03. Báo cáo chi tiết xuất kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k03",
    accessRoles: [ROLES["BAO_CAO"].CHI_TIET_XUAT_KHO],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K04. Báo cáo thẻ kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k04",
    accessRoles: [ROLES["BAO_CAO"].THE_KHO],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K05. Báo cáo chi tiết nhập kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k05",
    accessRoles: [ROLES["BAO_CAO"].CHI_TIET_NHAP_KHO],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K07. Biên bản kiểm kê tồn kho",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k07",
    accessRoles: [ROLES["BAO_CAO"].K07],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K08. Biên bản kiểm nhập",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k08",
    accessRoles: [ROLES["BAO_CAO"].K08],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K10. Báo cáo tổng hợp xuất",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k10",
    accessRoles: [ROLES["BAO_CAO"].K10],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K11. Báo cáo tồn kho theo lô",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k11",
    accessRoles: [ROLES["BAO_CAO"].K11],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K12. Báo cáo chi tiết sử dụng hàng hóa thông thường",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k12",
    accessRoles: [ROLES["BAO_CAO"].K12],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K13. Báo cáo tổng hợp nhập",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k13",
    accessRoles: [ROLES["BAO_CAO"].K13],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K14. Báo cáo chi tiết xuất thuốc ngoại trú",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k14",
    accessRoles: [ROLES["BAO_CAO"].K14],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "K01.2. Báo cáo nhập theo hàng hóa",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/k01_2",
    accessRoles: [ROLES["BAO_CAO"].K01_2],
    group: NHOM_BAO_CAO.BAO_CAO_KHO,
    capitalizeTitle: false,
  },
  {
    title: "KVT01.1. Báo cáo nhập kho theo nhà cung cấp",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/kvt01_1",
    accessRoles: [ROLES["BAO_CAO"].KVT01_1],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_VT_HC,
    capitalizeTitle: false,
  },
  {
    title: "KVT02. Báo cáo chi tiết sử dụng hàng hóa KTC",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/kvt02",
    accessRoles: [ROLES["BAO_CAO"].KVT02],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_VT_HC,
    capitalizeTitle: false,
  },
  {
    title: "KVT03. Báo cáo sử dụng hàng hóa KTC",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/kvt03",
    accessRoles: [ROLES["BAO_CAO"].KVT03],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_VT_HC,
    capitalizeTitle: false,
  },
  {
    title: "KNT01. Báo cáo thống kê thuốc bán theo bác sĩ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt01",
    accessRoles: [ROLES["BAO_CAO"].KNT01],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KNT02. Báo cáo tổng hợp thu tiền quầy thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt02",
    accessRoles: [ROLES["BAO_CAO"].KNT02],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KNT03. Bảng chi tiết thu quầy thuốc theo ngày",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt03",
    accessRoles: [ROLES["BAO_CAO"].KNT03],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KNT04. Báo cáo chi tiết thu tiền quầy thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt04",
    accessRoles: [ROLES["BAO_CAO"].KNT04],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KNT05. Bảng kê bán hàng tổng hợp",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt05",
    accessRoles: [ROLES["BAO_CAO"].KNT05],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KNT06. Sổ theo dõi khách hàng mua thuốc kiểm soát đặt biệt",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt06",
    accessRoles: [ROLES["BAO_CAO"].KNT06],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KNT07. Sổ theo dõi xuất nhập tồn thuốc kiểm soát đặc biệt",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/knt07",
    accessRoles: [],
    group: NHOM_BAO_CAO.BAO_CAO_KHO_NHA_THUOC,
    capitalizeTitle: false,
  },
  {
    title: "KSK01. Báo cáo kết quả khám sức khỏe hợp đồng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/ksk-01",
    accessRoles: [ROLES["BAO_CAO"].KSK01],
    group: NHOM_BAO_CAO.BAO_CAO_KHAM_SUC_KHOE,
    capitalizeTitle: false,
  },
  {
    title:
      "KSK02. Báo cáo thanh toán chi phí khám sức khỏe hợp đồng theo công ty",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/ksk-02",
    accessRoles: [ROLES["BAO_CAO"].KSK02],
    group: NHOM_BAO_CAO.BAO_CAO_KHAM_SUC_KHOE,
    capitalizeTitle: false,
  },
  {
    title: "KSK04 - Danh sách người bệnh lấy máu khám sức khỏe hợp đồng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/ksk-04",
    accessRoles: [ROLES["BAO_CAO"].KSK04],
    group: NHOM_BAO_CAO.BAO_CAO_KHAM_SUC_KHOE,
    capitalizeTitle: false,
  },
  {
    title: "KSK05 - Danh sách người bệnh khám sức khỏe hợp đồng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/ksk-05",
    accessRoles: [ROLES["BAO_CAO"].KSK05],
    group: NHOM_BAO_CAO.BAO_CAO_KHAM_SUC_KHOE,
    capitalizeTitle: false,
  },
  {
    title: "KSK12 - Danh sách công ty KSK theo trạng thái hợp đồng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/ksk-12",
    accessRoles: [ROLES["BAO_CAO"].KSK12],
    group: NHOM_BAO_CAO.BAO_CAO_KHAM_SUC_KHOE,
    capitalizeTitle: false,
  },
  {
    title: "G01 - Báo cáo chi tiết thực hiện dịch vụ gói theo người bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/g-01",
    accessRoles: [ROLES["BAO_CAO"].G01],
    group: NHOM_BAO_CAO.BAO_CAO_GOI_LIEU_TRINH,
    capitalizeTitle: false,
  },
  {
    title: "G02 - Báo cáo chi tiết thực hiện dịch vụ",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/g-02",
    accessRoles: [ROLES["BAO_CAO"].G02],
    group: NHOM_BAO_CAO.BAO_CAO_GOI_LIEU_TRINH,
    capitalizeTitle: false,
  },
  {
    title: "G03 - Báo cáo chi tiết dịch vụ theo phiếu thu thanh toán",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/g-03",
    accessRoles: [ROLES["BAO_CAO"].G03],
    group: NHOM_BAO_CAO.BAO_CAO_GOI_LIEU_TRINH,
    capitalizeTitle: false,
  },
  {
    title: "G04 - Báo cáo Tổng hợp doanh thu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/g-04",
    accessRoles: [ROLES["BAO_CAO"].G04],
    group: NHOM_BAO_CAO.BAO_CAO_GOI_LIEU_TRINH,
    capitalizeTitle: false,
  },
  {
    title: "KHTH01. Báo cáo hoạt động chuyên môn của trung tâm",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-01",
    accessRoles: [ROLES["BAO_CAO"].KHTH01],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "KHTH02. Thống kê người bệnh theo mặt bệnh",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-02",
    accessRoles: [ROLES["BAO_CAO"].KHTH02],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "KHTH03. Thống kê người bệnh ra viện",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-03",
    accessRoles: [ROLES["BAO_CAO"].KHTH03],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "KHTH04. Báo cáo công suất sử dụng giường",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-04",
    accessRoles: [ROLES["BAO_CAO"].KHTH04],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "KHTH05. Thống kê người bệnh chuyển tuyến",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-05",
    accessRoles: [ROLES["BAO_CAO"].KHTH05],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "KHTH06. Thống kê người bệnh tử vong",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-06",
    accessRoles: [ROLES["BAO_CAO"].KHTH06],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "KHTH07. Phản hồi thông tin người bệnh chuyển tuyến",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/khth-07",
    accessRoles: [ROLES["BAO_CAO"].KHTH07],
    group: NHOM_BAO_CAO.BAO_CAO_KE_HOACH_TONG_HOP,
    capitalizeTitle: false,
  },
  {
    title: "PTTT01. Danh sách phẫu thuật, thủ thuật",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/bao-cao/pttt-01",
    accessRoles: [],
    group: NHOM_BAO_CAO.BAO_CAO_PHAU_THUAT_THU_THUAT,
    capitalizeTitle: false,
  },
];

export const ListTiepDon = [
  {
    title: "Tiếp đón",
    i18n: "tiepDon.tiepDon",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/tiep-don",
  },
  {
    i18n: "tiepDon.danhSachNguoiBenhDaTiepDon",
    title: "Danh sách người bệnh đã tiếp đón",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-ly-tiep-don/danh-sach-nb-da-tiep-don",
  },
  {
    i18n: "tiepDon.danhSachNguoiBenhHuyTiepDon",
    title: "Danh sách NB hủy tiếp đón",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-ly-tiep-don/danh-sach-nb-huy-tiep-don",
  },
];

export const ListQuanLyNoiTru = [
  {
    title: "Danh sách lập bệnh án",
    i18n: "lapBenhAn.danhSachLapBenhAn",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-ly-noi-tru/danh-sach-lap-benh-an",
    accessRoles: [ROLES["QUAN_LY_NOI_TRU"].DANH_SACH_LAP_BENH_AN],
  },
  {
    title: "Danh sách người bệnh nội trú",
    i18n: "quanLyNoiTru.danhSachNguoiBenhNoiTru",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-ly-noi-tru/danh-sach-nguoi-benh-noi-tru",
    accessRoles: [ROLES["QUAN_LY_NOI_TRU"].DANH_SACH_NB_NOI_TRU],
  },
  {
    title: "Gia hạn thẻ, chuyển đối tượng",
    i18n: "quanLyNoiTru.giaHanThe.giaHanTheChuyenDoiTuong",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/quan-ly-noi-tru/gia-han-the-chuyen-doi-tuong",
    accessRoles: [ROLES["QUAN_LY_NOI_TRU"].DANH_SACH_NB_NOI_TRU],
  },
];

export const ListKhamSucKhoe = [
  {
    title: "Danh sách phiếu báo giá",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/kham-suc-khoe/phieu-bao-gia",
  },
  {
    title: "Danh sách hợp đồng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/kham-suc-khoe/hop-dong",
  },
];

export const ListSinhHieu = [
  {
    title: "Sinh Hiệu",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/sinh-hieu/ds-sinh-hieu",
  },
];

export const ListNhaThuoc = [
  {
    title: "Danh sách đơn thuốc",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/nha-thuoc",
  },
  {
    title: "Liên thông GPP",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/nha-thuoc/lien-thong-gpp",
  },
];

export const ListGoiDichVu = [
  {
    title: "Danh sách người bệnh sử dụng gói",
    i18n: "goiDichVu.danhSachNguoiBenhSuDungGoi",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/goi-dich-vu/danh-sach-su-dung-goi",
    accessRoles: [ROLES["GOI_DICH_VU"].DANH_SACH_NB_SU_DUNG_GOI_DICH_VU],
  },
  {
    title: "Danh mục gói dịch vụ",
    bg: require("assets/images/pagehome/bgThietLap.png"),
    link: "/goi-dich-vu/danh-muc",
    accessRoles: [ROLES["GOI_DICH_VU"].GOI_DICH_VU],
  },
];

export const ListPhauThuatThuThuat = [
  {
    title: "Danh sách phẫu thuật- thủ thuật",
    i18n: "pttt.danhSachPhauThuatThuThuat",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/phau-thuat-thu-thuat/danh-sach-nguoi-benh",
  },
];

export const ListGiayDayCong = [
  {
    title: "Danh sách giấy nghỉ hưởng",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/giay-day-cong/giay-nghi-huong",
  },
  {
    title: "Danh sách người bệnh tử vong",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/giay-day-cong/nb-tu-vong",
  },
  {
    title: "Danh sách người bệnh ra viện",
    bg: require("assets/images/pagehome/icChucNang1.png"),
    link: "/giay-day-cong/nb-ra-vien",
  },
];

export const ListDashboard = [
  {
    title: "Trình chiếu TV",
    bg: require("assets/images/pagehome/bgTrinhChieu.png"),
    link: "/dashboard/trinh-chieu-tv",
  },
];
